### ISSUE TITLE
crash on begin play: Object is not packaged: RpaiState_Map None

### ISSUE THREAD

**Issue by pamela-worgen** [hollsteinm/ReasonablePlanningAI#1]
Object is not packaged: RpaiState_Map None

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp] [Line: 2370] Object is not packaged: RpaiState_Map None

UnrealEditor_CoreUObject!StaticAllocateObjectErrorTests() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp:2370]
UnrealEditor_CoreUObject!StaticAllocateObject() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp:2426]
UnrealEditor_CoreUObject!StaticConstructObject_Internal() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp:3516]
UnrealEditor_ReasonablePlanningAI!NewObject<URpaiState>() [C:\UE_5.0\Engine\Source\Runtime\CoreUObject\Public\UObject\UObjectGlobals.h:1405]
UnrealEditor_ReasonablePlanningAI!URpaiBrainComponent::LoadOrCreateStateFromAi() [D:\ue-projects\ueproject\Plugins\ReasonablePlanningAI-main\Source\ReasonablePlanningAI\Private\Core\RpaiBrainComponent.cpp:257]
UnrealEditor_ReasonablePlanningAI!URpaiBrainComponent::StartLogic() [D:\ue-projects\ueproject\Plugins\ReasonablePlanningAI-main\Source\ReasonablePlanningAI\Private\Core\RpaiBrainComponent.cpp:188]
UnrealEditor_CoreUObject!UFunction::Invoke() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5912]
UnrealEditor_CoreUObject!UObject::CallFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1012]
UnrealEditor_CoreUObject!ProcessLocalScriptFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1082]
UnrealEditor_CoreUObject!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:912]
UnrealEditor_CoreUObject!ProcessLocalFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1143]
UnrealEditor_CoreUObject!ProcessLocalScriptFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1082]
UnrealEditor_CoreUObject!UObject::ProcessInternal() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1170]
UnrealEditor_CoreUObject!UFunction::Invoke() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5912]
UnrealEditor_CoreUObject!UObject::ProcessEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2003]
UnrealEditor_Engine!UActorComponent::BeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Components\ActorComponent.cpp:1045]
UnrealEditor_Engine!AActor::BeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:3887]
UnrealEditor_Engine!AActor::DispatchBeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:3849]
UnrealEditor_Engine!AWorldSettings::NotifyBeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\WorldSettings.cpp:283]
UnrealEditor_Engine!AGameStateBase::HandleBeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\GameStateBase.cpp:205]
UnrealEditor_Engine!UWorld::BeginPlay() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\World.cpp:4908]
UnrealEditor_Engine!UGameInstance::StartPlayInEditorGameInstance() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\GameInstance.cpp:500]
UnrealEditor_UnrealEd!UEditorEngine::CreateInnerProcessPIEGameInstance() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:3052]
UnrealEditor_UnrealEd!UEditorEngine::OnLoginPIEComplete_Deferred() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1568]
UnrealEditor_UnrealEd!UEditorEngine::CreateNewPlayInEditorInstance() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1830]
UnrealEditor_UnrealEd!UEditorEngine::StartPlayInEditorSession() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:2798]
UnrealEditor_UnrealEd!UEditorEngine::StartQueuedPlaySessionRequestImpl() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1148]
UnrealEditor_UnrealEd!UEditorEngine::StartQueuedPlaySessionRequest() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1051]
UnrealEditor_UnrealEd!UEditorEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1665]
UnrealEditor_UnrealEd!UUnrealEdEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:474]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5215]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:183]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:147]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:283]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:330]
UnrealEditor!__scrt_common_main_seh() [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by pamela-worgen** [comment]
I followed the guide on setting up the ComposerBehaviorExample but the above error is triggering every time on clicking play, I've included a uasset that includes how i set it up. 

Perhaps you can create an example one for the content folder so devs can duplicate from and start from a base?

Thanks!


[DT_ComposerBehaviorExample.zip](https://github.com/hollsteinm/ReasonablePlanningAI/files/10137067/DT_ComposerBehaviorExample.zip)

**Comment by hollsteinm** [comment]
Thank you for reporting this issue. May I please have the version of unreal engine you are using as well as the commit hash for the plugin you are using (or the tag or branch)?

Thank you for the excellent idea of packaging up the example!

**Comment by pamela-worgen** [comment]
Version: 5.0.3-20979098+++UE5+Release-5.0

the latest version of the repo: [4e0d30e](https://github.com/hollsteinm/ReasonablePlanningAI/commit/4e0d30e9101c8acbf08c824c3fdb8cd631b797e6)

**Comment by hollsteinm** [comment]
Thank you. That error is reported when a `nullptr` is passed as the root for the `NewObject` call. This triggers logic to search for the package. The reason `nullptr` was passed was because the call to the base class `UBrainComponent::GetAIOwner()` function returned a `nullptr`. This happens when the `URpaiBrainComponent` is added as a component to an Actor, Pawn, or Character instead of the `AIController` for said Pawn or Character.

While I could have just left it as that, I did add a `URpaiBrainComponent::BeginPlay()` check to force resolving the AIOwner (if nullptr) by getting the owner of the component and seeing if it has a controller that is an `AAIController`. If the AIOwner field ultimately cannot be resolved, a fatal message is logged.

Please let me know if this does not solve your issue. If I do not hear back in 7 days I will close this issue as resolved.

**Comment by pamela-worgen** [comment]
I must have been adding it to the pawn class. doh! 

Anyways, adding it to my bp ai controller class did fix it. Well done, thank you!
